{{ if not .Values.Installation.V1.Provider.AWS.Route53.Enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: route53-manager-secret
  namespace: giantswarm
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.Route53Manager.SecretYaml | b64enc | quote }}
{{ end }}
