{{ if .Values.route53Manager.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: route53-manager-secret
  namespace: giantswarm
data:
  secret.yaml: {{ .Values.secretYaml | b64enc | quote }}
{{ end }}
