apiVersion: v1
kind: ConfigMap
metadata:
  name: route53-manager-configmap
  namespace: giantswarm
data:
  config.yaml: |
{{ if .Values.route53Manager.enabled }}
    service:
      installation:
        name: '{{ .Values.codename }}'
{{ end }}
