apiVersion: v1
kind: ConfigMap
metadata:
  name: route53-manager-configmap
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    service:
      installation:
        name: '{{ .Values.Installation.V1.Name }}'
