apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      # Job timeout
      activeDeadlineSeconds: 600
      template:
        spec:
          volumes:
          - name: route53-manager-configmap
            configMap:
              name: route53-manager-configmap
              items:
              - key: config.yaml
                path: config.yaml
          - name: route53-manager-secret
            secret:
              secretName: route53-manager-secret
              items:
              - key: secret.yaml
                path: secret.yaml
          serviceAccountName: {{ .Values.name }}
          securityContext:
            runAsUser: {{ .Values.userID }}
            runAsGroup: {{ .Values.groupID }}
          containers:
          - name: route53-manager
            image: quay.io/giantswarm/route53-manager:[[ .SHA ]]
            volumeMounts:
            - name: route53-manager-configmap
              mountPath: /var/run/route53-manager/configmap/
              readOnly: true
            - name: route53-manager-secret
              mountPath: /var/run/route53-manager/secret/
              readOnly: true
            args:
            - sync
            - --config.dirs=/var/run/route53-manager/configmap/
            - --config.dirs=/var/run/route53-manager/secret/
            - --config.files=config
            - --config.files=secret
          restartPolicy: Never
